### ISSUE TITLE
一个布尔tensor跟‘-’不匹配的问题

### ISSUE THREAD

**Issue by Ericzh2017** [PengjieRen/GLKS#3]
按照说明预处理并导入数据以后，运行报错，布尔tensor跟‘-’不匹配。
我自己尝试了很久还是没有跑通。
  File "/home/cike/KSChat/GLKS/GLKS.py", line 80, in forward
    b_score=self.match(b_enc_output, c_enc_output, c_state, b_mask, c_mask)
  File "/home/cike/KSChat/GLKS/GLKS.py", line 55, in match
    matching = matching.masked_fill(1 - c_mask.unsqueeze(1), -float('inf'))
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 320, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the - operator, with a bool tensor is not supported. If you are trying to invert a mask, use the ~ or bitwise_not() operator instead.
请问一下这可能是什么原因导致的呢？
$ python -m torch.distributed.launch --nproc_per_node=1 Run_GLKS.py --mode='train'
1.2.0.dev20190805
10.0.130
7602
item size: 21704
data size: 34486
no_init b_encoder.c_embedding.0.weight torch.Size([21704, 300])
init b_encoder.c_encs.0.weight_ih_l0 torch.Size([384, 300])
init b_encoder.c_encs.0.weight_hh_l0 torch.Size([384, 128])
init b_encoder.c_encs.0.bias_ih_l0 torch.Size([384])
init b_encoder.c_encs.0.bias_hh_l0 torch.Size([384])
init b_encoder.c_encs.0.weight_ih_l0_reverse torch.Size([384, 300])
init b_encoder.c_encs.0.weight_hh_l0_reverse torch.Size([384, 128])
init b_encoder.c_encs.0.bias_ih_l0_reverse torch.Size([384])
init b_encoder.c_encs.0.bias_hh_l0_reverse torch.Size([384])
no_init c_encoder.c_embedding.0.weight torch.Size([21704, 300])
init c_encoder.c_encs.0.weight_ih_l0 torch.Size([384, 300])
init c_encoder.c_encs.0.weight_hh_l0 torch.Size([384, 128])
init c_encoder.c_encs.0.bias_ih_l0 torch.Size([384])
init c_encoder.c_encs.0.bias_hh_l0 torch.Size([384])
init c_encoder.c_encs.0.weight_ih_l0_reverse torch.Size([384, 300])
init c_encoder.c_encs.0.weight_hh_l0_reverse torch.Size([384, 128])
init c_encoder.c_encs.0.bias_ih_l0_reverse torch.Size([384])
init c_encoder.c_encs.0.bias_hh_l0_reverse torch.Size([384])
no_init embedding.weight torch.Size([21704, 300])
init state_tracker.linear.weight torch.Size([256, 512])
init state_tracker.linear.bias torch.Size([256])
init state_tracker.gru.weight_ih_l0 torch.Size([768, 300])
init state_tracker.gru.weight_hh_l0 torch.Size([768, 256])
init state_tracker.gru.bias_ih_l0 torch.Size([768])
init state_tracker.gru.bias_hh_l0 torch.Size([768])
init k_selector.b_highway.nonlinear.0.weight torch.Size([512, 512])
init k_selector.b_highway.nonlinear.0.bias torch.Size([512])
init k_selector.b_highway.nonlinear.1.weight torch.Size([512, 512])
init k_selector.b_highway.nonlinear.1.bias torch.Size([512])
init k_selector.b_highway.linear.0.weight torch.Size([512, 512])
init k_selector.b_highway.linear.0.bias torch.Size([512])
init k_selector.b_highway.linear.1.weight torch.Size([512, 512])
init k_selector.b_highway.linear.1.bias torch.Size([512])
init k_selector.b_highway.gate.0.weight torch.Size([512, 512])
init k_selector.b_highway.gate.0.bias torch.Size([512])
init k_selector.b_highway.gate.1.weight torch.Size([512, 512])
init k_selector.b_highway.gate.1.bias torch.Size([512])
init k_selector.c_highway.nonlinear.0.weight torch.Size([512, 512])
init k_selector.c_highway.nonlinear.0.bias torch.Size([512])
init k_selector.c_highway.nonlinear.1.weight torch.Size([512, 512])
init k_selector.c_highway.nonlinear.1.bias torch.Size([512])
init k_selector.c_highway.linear.0.weight torch.Size([512, 512])
init k_selector.c_highway.linear.0.bias torch.Size([512])
init k_selector.c_highway.linear.1.weight torch.Size([512, 512])
init k_selector.c_highway.linear.1.bias torch.Size([512])
init k_selector.c_highway.gate.0.weight torch.Size([512, 512])
init k_selector.c_highway.gate.0.bias torch.Size([512])
init k_selector.c_highway.gate.1.weight torch.Size([512, 512])
init k_selector.c_highway.gate.1.bias torch.Size([512])
init k_selector.match_attn.linear_key.weight torch.Size([512, 512])
init k_selector.match_attn.linear_query.weight torch.Size([512, 512])
init k_selector.match_attn.linear_query.bias torch.Size([512])
init k_selector.match_attn.v.weight torch.Size([1, 512])
init k_selector.area_attn.linear_key.weight torch.Size([256, 256])
init k_selector.area_attn.linear_query.weight torch.Size([256, 256])
init k_selector.area_attn.linear_query.bias torch.Size([256])
init k_selector.area_attn.v.weight torch.Size([1, 256])
init c_generator.b_attn.linear_key.weight torch.Size([256, 256])
init c_generator.b_attn.linear_query.weight torch.Size([256, 812])
init c_generator.b_attn.linear_query.bias torch.Size([256])
init c_generator.b_attn.v.weight torch.Size([1, 256])
init v_generator.c_attn.linear_key.weight torch.Size([256, 256])
init v_generator.c_attn.linear_query.weight torch.Size([256, 812])
init v_generator.c_attn.linear_query.bias torch.Size([256])
init v_generator.c_attn.v.weight torch.Size([1, 256])
init v_generator.b_attn.linear_key.weight torch.Size([256, 256])
init v_generator.b_attn.linear_query.weight torch.Size([256, 812])
init v_generator.b_attn.linear_query.bias torch.Size([256])
init v_generator.b_attn.v.weight torch.Size([1, 256])
init v_generator.readout.weight torch.Size([256, 1324])
init v_generator.readout.bias torch.Size([256])
init v_generator.generator.weight torch.Size([21704, 256])
init v_generator.generator.bias torch.Size([21704])
init mixture.linear1.weight torch.Size([1, 256])
init mixture.linear1.bias torch.Size([1])
GPU 0
Traceback (most recent call last):
File "Run_GLKS.py", line 109, in 
train(args)
File "Run_GLKS.py", line 61, in train
trainer.train_epoch('ds_mle_mcc_train', train_dataset, collate_fn, batch_size, i, model_optimizer)
File "/home/cike/KSChat/GLKS/trainers/DefaultTrainer.py", line 88, in train_epoch
bloss = self.train_batch(epoch, data, method=method, optimizer=optimizer)
File "/home/cike/KSChat/GLKS/trainers/DefaultTrainer.py", line 43, in train_batch
loss = self.model(data, method=method)
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in call
result = self.forward(*input, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 442, in forward
output = self.module(*inputs[0], **kwargs[0])
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in call
result = self.forward(*input, **kwargs)
File "/home/cike/KSChat/GLKS/GLKS.py", line 259, in forward
return self.do_train(data, type=method)
File "/home/cike/KSChat/GLKS/GLKS.py", line 268, in do_train
encode_output, init_decoder_state, all_decode_output, all_gen_output = decode_to_end(self, data, self.vocab2id, tgt=data['response'])
File "/home/cike/KSChat/GLKS/Utils.py", line 65, in decode_to_end
encode_outputs = model.encode(data)
File "/home/cike/KSChat/GLKS/GLKS.py", line 214, in encode
segment, p_s, p_g =self.k_selector(b_enc_output, c_enc_output, c_state, data['unstructured_knowledge'].ne(0), data['context'].ne(0))
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in call
result = self.forward(*input, **kwargs)
File "/home/cike/KSChat/GLKS/GLKS.py", line 80, in forward
b_score=self.match(b_enc_output, c_enc_output, c_state, b_mask, c_mask)
File "/home/cike/KSChat/GLKS/GLKS.py", line 55, in match
matching = matching.masked_fill(1 - c_mask.unsqueeze(1), -float('inf'))
File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 320, in rsub
return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the - operator, with a bool tensor is not supported. If you are trying to invert a mask, use the ~ or bitwise_not() operator instead.
Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 246, in 
main()
File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 242, in main
cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-u', 'Run_GLKS.py', '--local_rank=0', '--mode=train']' returned non-zero exit status 1.

**Comment by PengjieRen** [comment]
你好，
这是pytorch版本问题，应该是从pytorch 1.2 版本开始bool tensor不支持减法了，解决方案是用1.1版本，或者1- bool tensor改成 ~bool tensor.

**Comment by Ericzh2017** [comment]
非常感谢Ren同学。再请教一下，在载入第四个batch的数据的时候，出现了维度不匹配的问题。请问这也是由于torch版本问题导致的吗？
Method ds_mle_mcc_train Epoch 0 Batch  1 Loss  [6.057840347290039, 0.0018790364265441895, 0.5616985559463501, 0.835719645023346] Time  0.5343761444091797
Method ds_mle_mcc_train Epoch 0 Batch  101 Loss  [4.233457088470459, 0.08567094802856445, 0.5802528858184814, 0.8713107705116272] Time  40.51655459403992
Method ds_mle_mcc_train Epoch 0 Batch  201 Loss  [2.368910551071167, 0.07132136821746826, 0.6401641368865967, 0.7776915431022644] Time  80.67992901802063
Traceback (most recent call last):
  File "Run_GLKS.py", line 109, in <module>
    train(args)
  File "Run_GLKS.py", line 61, in train
    trainer.train_epoch('ds_mle_mcc_train', train_dataset, collate_fn, batch_size, i, model_optimizer)
  File "/home/cike/KSChat/GLKS/trainers/DefaultTrainer.py", line 77, in train_epoch
    for j, data in enumerate(train_loader, 0):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/cike/KSChat/GLKS/GLKSDataset.py", line 157, in collate_fn
    'selection': torch.cat(selection),
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 75 and 93 in dimension 1 at /pytorch/aten/src/TH/generic/THTensor.cpp:691

**Comment by Ericzh2017** [comment]
在一台安装了torch1.1的服务器上面重新运行了一遍Prepare_holl.py就可以跑通了，应该是版本原因导致的问题

**Comment by ValkyriaLenneth** [comment]
> 在一台安装了torch1.1的服务器上面重新运行了一遍Prepare_holl.py就可以跑通了，应该是版本原因导致的问题

您好，能详细说明一下么，我也遇到了这个问题。但是我是全程在torch1.1的服务器上运行的，重新跑了一遍Prepare_holl.py仍然出现同样结果。
